version: 0.2

phases:
  install:
    commands:
      - echo Installing Java 21
      - wget https://corretto.aws/downloads/latest/amazon-corretto-21-x64-linux-jdk.tar.gz
      - tar -xzf amazon-corretto-21-x64-linux-jdk.tar.gz
      - export JAVA_HOME=$(pwd)/amazon-corretto-21*
      - export PATH=$JAVA_HOME/bin:$PATH
      - java -version

  build:
    commands:
      - echo Build started
      - mvn clean package

artifacts:
  files:
    - target/*.jar