version: 0.2

phases:
  install:
    commands:
      - echo Installing Java 21
      - yum update -y
      - yum install -y java-21-amazon-corretto-devel
      - export JAVA_HOME=/usr/lib/jvm/java-21-amazon-corretto
      - export PATH=$JAVA_HOME/bin:$PATH
      - echo $JAVA_HOME
      - java -version

  build:
    commands:
      - chmod +x mvnw
      - ./mvnw clean package -DskipTests

artifacts:
  files:
    - target/*.jar